### ISSUE TITLE
Not sure whats going on here.

### ISSUE THREAD

**Issue by whitebook** [leafo/lapis-systemd#1]
lapis systemd service development --trace
Error: /usr/local/share/lua/5.1/lapis/cmd/util.lua:151: attempt to call method 'match' (a nil value)
stack traceback:
    /usr/local/share/lua/5.1/lapis/cmd/util.lua:151: in function 'parse_flags'
    ...sr/local/share/lua/5.1/lapis/cmd/actions/systemd.lua:10: in function <...sr/local/share/lua/5.1/lapis/cmd/actions/systemd.lua:9>
    (tail call): ?
    [C]: in function 'xpcall'
    /usr/local/share/lua/5.1/lapis/cmd/actions.lua:323: in function 'execute'
    ...usr/local/lib/luarocks/rocks/lapis/1.5.1-1/bin/lapis:4: in main chunk
    [C]: ?

**Comment by TangentFoxy** [comment]
_Annnd_ I'm getting the same error... :/

Any ideas?
