### ISSUE TITLE
Not on LuaRocks?

### ISSUE THREAD

**Issue by TangentFoxy** [leafo/lapis-systemd#3]
Running `luarocks install lapis-systemd` returns `Error: No results matching query were found.` :/

**Comment by leafo** [comment]
It's located on the development manifest https://luarocks.org/modules/leafo/lapis-systemd

Will release a full version soon

**Comment by ghost** [comment]
`luarocks install --server=http://luarocks.org/dev lapis-systemd`

https://luarocks.org/modules/leafo/lapis-systemd
